---
# Personal preference
- name: Remove System apps
  dnf:
    name:
      - evolution
      - gnome-calendar
      - gnome-contacts
      - gnome-maps
      - rhythmbox
    state: absent

- name: Add RPM Fusion
  dnf:
    name:
      - 'https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{fedora_version}}.noarch.rpm'
      - 'https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{fedora_version}}.noarch.rpm'
    state: present

- name: Install and Update RPMs
  dnf:
    name: "{{ dnf_packages }}"
    state: present

# Install a package group
- name: Install Dev packs
  dnf:
    name:
      - "@Development Tools"
      - "@RPM Development Tools"
    state: latest

###################
# Include Section #
###################
- include: vscode.yml
